import express from 'express';
import chat from './api/chat.js';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { handleUpgrade } from './lib/wisp.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const app=express();
app.use((req,res,next)=>{res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','credentialless');next();});
app.all('/api/chat',chat);
app.use(express.static(path.join(root,'public')));
const server=http.createServer(app);
server.on('upgrade',handleUpgrade);
const port = Number(process.env.PORT) || 3000;
server.listen(port,'127.0.0.1',()=>console.log(`Neon Arcade is ready: http://localhost:${port}`));
