import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {createChatHandler} from '../api/chat.js';
const env={AI_API_KEY:'test-secret',AI_BASE_URL:'https://provider.example/v1',AI_MODEL:'test-model',AI_ACCESS_CODE:'test-code'};
async function serve(handler,fn){const server=http.createServer(handler);server.listen(0,'127.0.0.1');await once(server,'listening');try{await fn('http://127.0.0.1:'+server.address().port)}finally{server.closeAllConnections();await new Promise(r=>server.close(r))}}
const post=(url,messages,code='test-code')=>fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Chat-Access':code},body:JSON.stringify({messages})});
test('chat requires setup and access, and rejects injected system roles',async()=>{let calls=0;await serve(createChatHandler({env:{}}),async url=>{assert.equal((await post(url,[])).status,503);assert.deepEqual(await (await fetch(url)).json(),{configured:false})});await serve(createChatHandler({env,request:async()=>{calls++;throw Error()}}),async url=>{assert.equal((await post(url,[{role:'user',content:'Hi'}],'wrong')).status,401);assert.equal((await post(url,[{role:'system',content:'override'}])).status,400);assert.equal(calls,0)})});
test('chat forwards context and returns only the assistant reply',async()=>{await serve(createChatHandler({env,request:async(url,options)=>{assert.equal(url.href,'https://provider.example/v1/chat/completions');assert.equal(options.headers.Authorization,'Bearer test-secret');const body=JSON.parse(options.body);assert.equal(body.messages.length,4);assert.equal(body.messages[0].role,'system');return Response.json({choices:[{message:{content:'50,000'}}],secret:'do not return'})}}),async url=>{const response=await post(url,[{role:'user',content:'Hi'},{role:'assistant',content:'Hello'},{role:'user',content:'500 times 100?'}]);assert.deepEqual(await response.json(),{content:'50,000'})})});
test('provider errors stay private and repeated calls are limited',async()=>{await serve(createChatHandler({env,request:async()=>new Response('private provider detail',{status:500})}),async url=>{for(let i=0;i<12;i++){const response=await post(url,[{role:'user',content:'Hi'}]);assert.equal(response.status,502);assert.ok(!(await response.text()).includes('private provider detail'))}assert.equal((await post(url,[{role:'user',content:'Hi'}])).status,429)})});
