import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {randomUUID} from 'node:crypto';
import {WebSocket,WebSocketServer} from '../remote-relay/node_modules/ws/wrapper.mjs';
import {createRelay} from '../remote-relay/relay.mjs';
import {connectDevice} from '../remote-access/device-client.mjs';
import {safePath,origin,filterHeaders,MAX_BUFFER,send} from '../remote-relay/protocol.mjs';
import {createDatabase} from '../remote-relay/database.mjs';
import {createOwnerRelay} from '../accounts/api/owner-relay.js';
import retired from '../accounts/api/owner-remote.js';
import {ownerPath} from '../accounts/owner-portal.js';
const token='verified-owner-'.repeat(5),account='https://neon-arcade-improvedv3.vercel.app';
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function listen(server){server.listen(0,'127.0.0.1');await once(server,'listening');return 'http://127.0.0.1:'+server.address().port;}
async function eventually(fn){for(let i=0;i<80;i++){if(fn())return;await pause(10);}assert.ok(fn(),'Expected state change');}
async function setup(t,{interval=100000}={}){
 const deviceId=randomUUID(),deviceSecret='b'.repeat(64),sessionKey='c'.repeat(64);
 let allowed=true,mfa=true,deviceAllowed=true,online=false,audit=true,time=Date.now(),grant=null,seen,input=[];const logs=[];
 const db={owner:async(jwt,args)=>{if(jwt!==token||!allowed||!mfa){const error=Error('Denied');error.status=403;throw error;}
  if(args.operation==='devices')return [{id:deviceId,label:'Test PC',online}];
  if(args.operation==='start'){grant={id:randomUUID(),device_id:deviceId,expires_at:new Date(time+600000).toISOString()};logs.push('session-started');return {...grant,secret:sessionKey};}
  if(args.operation==='stop'){grant=null;logs.push('owner-ended');return {};}
  if(args.operation==='revoke'){deviceAllowed=false;grant=null;logs.push('device-revoked');return {};}
  return [];
 },device:async(id,key,state)=>{if(id!==deviceId||key!==deviceSecret||!deviceAllowed)return false;if(state==='online')online=true;if(state==='offline')online=false;return true;},session:async(key,operation='check',detail='')=>{if(key!==sessionKey) return null;if(operation==='end'){logs.push('session-ended:'+detail);grant=null;return {};}
  if(!allowed||!mfa||!deviceAllowed||!grant)return null;if(!audit)throw Error('Audit unavailable');if(operation==='action')logs.push(detail);return grant;}};
 const upstream=http.createServer((req,res)=>{seen=req.headers;let payload='';req.on('data',chunk=>payload+=chunk);req.on('end',()=>{res.setHeader('Set-Cookie','upstream=secret');res.setHeader('Content-Type','text/plain');res.end('desktop:'+payload);});});
 const upstreamWs=new WebSocketServer({server:upstream});upstreamWs.on('connection',(socket,req)=>{seen=req.headers;socket.on('message',(data,binary)=>{input.push(data.toString());socket.send(data,{binary});});});
 const upstreamURL=await listen(upstream),allocation=http.createServer(),relayURL=await listen(allocation);await new Promise(resolve=>allocation.close(resolve));
 const relay=createRelay({publicOrigin:relayURL,db,accountOrigins:[account],local:true,now:()=>time,checkInterval:interval});relay.server.listen(Number(new URL(relayURL).port),'127.0.0.1');await once(relay.server,'listening');
 function agent(){return connectDevice({relayOrigin:relayURL,deviceId,deviceSecret,ownerUsername:'acxel'},{local:true,httpRequest:(options,callback)=>{assert.equal(options.hostname,'127.0.0.1');assert.equal(options.port,8080);return http.request({...options,port:Number(new URL(upstreamURL).port)},callback);},WebSocketClass:class extends WebSocket{constructor(url,...args){super(url.startsWith('ws://127.0.0.1:8080')?url.replace('ws://127.0.0.1:8080',upstreamURL.replace('http','ws')):url,...args);}}});}
 const client=agent();await once(client.socket,'open');await eventually(()=>online);
 t.after(async()=>{client.close();for(const socket of upstreamWs.clients)socket.terminate();upstreamWs.close();upstream.closeAllConnections();await relay.close();await new Promise(resolve=>upstream.close(resolve));});
 const control=(operation,extra={},jwt=token,orig=account)=>fetch(relayURL+'/neon/control',{method:'POST',headers:{Authorization:'Bearer '+jwt,Origin:orig,'Content-Type':'application/json'},body:JSON.stringify({operation,...extra})});
 const redeem=ticket=>fetch(relayURL+'/neon/redeem',{method:'POST',headers:{Origin:relayURL,'Content-Type':'application/json'},body:JSON.stringify({ticket})});
 async function session(){const response=await control('start',{device_id:deviceId});assert.equal(response.status,200);const data=await response.json();assert.equal(data.url.includes(token),false);assert.equal(data.url.includes(sessionKey),false);const response2=await redeem(new URL(data.url).hash.slice(1));assert.equal(response2.status,200);return {cookie:response2.headers.get('set-cookie').split(';')[0],id:data.id};}
 const ws=cookie=>new WebSocket(relayURL.replace('http','ws')+'/api/stream',{headers:{Origin:relayURL,Cookie:cookie}});
 return {relayURL,deviceId,control,redeem,session,ws,logs,seen:()=>seen,input,client,deny:()=>allowed=false,noMfa:()=>mfa=false,noAudit:()=>audit=false,revoke:()=>deviceAllowed=false,advance:ms=>time+=ms};
}
test('retired remote URL never contacts the PC',async t=>{const server=http.createServer(retired);const url=await listen(server);t.after(()=>server.close());for(const method of ['GET','POST'])assert.equal((await fetch(url,{method})).status,410);});
test('owner routes match fixed pages only',()=>{for(const route of ['/owner','/owner/users','/owner/devices','/owner/remote','/owner/logs'])assert.notEqual(ownerPath(route),null);for(const route of ['/owners','/owner/evil','/owner/users/other'])assert.equal(ownerPath(route),null);});
test('desktop paths, origins and injected headers cannot change the fixed target',()=>{for(const path of ['https://evil.test/','//evil.test/','/neon/device','/\\evil','/hello\r\nHeader'])assert.throws(()=>safePath(path));assert.equal(safePath('/api/stream?id=1'),'/api/stream?id=1');assert.throws(()=>origin('http://evil.test'));assert.throws(()=>origin('https://evil.test/path'));const headers=filterHeaders({authorization:'secret',cookie:'secret','x-neon-remote-user':'attacker',host:'evil',range:'bytes=0-2'});assert.deepEqual(headers,{range:'bytes=0-2'});assert.throws(()=>send({readyState:1,bufferedAmount:MAX_BUFFER+1},'x'));});
test('owner and MFA are required even when a caller discovers the relay API',async t=>{const s=await setup(t);assert.equal((await s.control('devices',{},'member-token-'.repeat(5))).status,403);assert.equal((await s.control('devices',{},token,'https://neongoatarcadd.vercel.app')).status,403);s.noMfa();assert.equal((await s.control('devices')).status,403);assert.equal((await fetch(s.relayURL+'/')).status,403);});
test('one-use launch tickets establish secure isolated cookies and resist replay',async t=>{const s=await setup(t);const response=await s.control('start',{device_id:s.deviceId});const data=await response.json(),ticket=new URL(data.url).hash.slice(1);const first=await s.redeem(ticket);assert.equal(first.status,200);const cookie=first.headers.get('set-cookie');assert.match(cookie,/HttpOnly; Secure; SameSite=Strict/);assert.equal((await s.redeem(ticket)).status,403);assert.ok(s.logs.includes('session-opened'));});
test('expired tickets and expired sessions cannot reach a desktop',async t=>{const s=await setup(t);const data=await (await s.control('start',{device_id:s.deviceId})).json();s.advance(30001);assert.equal((await s.redeem(new URL(data.url).hash.slice(1))).status,403);const {cookie}=await s.session();s.advance(600001);assert.equal((await fetch(s.relayURL+'/',{headers:{Cookie:cookie}})).status,403);assert.ok(s.logs.includes('session-ended:expired'));});
test('HTTP reaches the streamer through the outbound channel without leaking credentials',async t=>{const s=await setup(t);const {cookie}=await s.session();const response=await fetch(s.relayURL+'/api/control',{method:'POST',headers:{Cookie:cookie,Origin:s.relayURL,Authorization:'Bearer '+token,'X-Neon-Remote-User':'evil','Content-Type':'text/plain'},body:'hello'});assert.equal(response.status,200);assert.equal(await response.text(),'desktop:hello');assert.equal(response.headers.get('set-cookie'),null);assert.equal(s.seen()['x-neon-remote-user'],'acxel');assert.equal(s.seen().authorization,undefined);assert.equal(s.seen().cookie,undefined);assert.ok(s.logs.includes('desktop-request'));});
test('WebSocket controls traverse the outbound connection and recheck role before each input',async t=>{const s=await setup(t);const {cookie}=await s.session();const socket=s.ws(cookie);socket.on('error',()=>{});await once(socket,'open');socket.send('mouse');const [reply]=await once(socket,'message');assert.equal(reply.toString(),'mouse');assert.ok(s.logs.includes('stream-opened'));s.deny();const closed=once(socket,'close');socket.send('denied-input');await closed;assert.deepEqual(s.input,['mouse']);assert.ok(s.logs.includes('session-ended:revoked'));});
test('idle open streams close after device revocation',async t=>{const s=await setup(t,{interval:100});const {cookie}=await s.session(),socket=s.ws(cookie);socket.on('error',()=>{});await once(socket,'open');const closed=once(socket,'close');s.revoke();await closed;assert.equal((await fetch(s.relayURL+'/',{headers:{Cookie:cookie}})).status,403);});
test('database audit failures fail closed before desktop actions',async t=>{const s=await setup(t);const {cookie}=await s.session();s.noAudit();assert.equal((await fetch(s.relayURL+'/api/control',{method:'POST',headers:{Cookie:cookie,Origin:s.relayURL}})).status,403);assert.equal(s.seen(),undefined);});
test('ending a session or unplugging the PC removes browser access',async t=>{const s=await setup(t);const {cookie,id}=await s.session();assert.equal((await s.control('stop',{session_id:id})).status,200);assert.equal((await fetch(s.relayURL+'/',{headers:{Cookie:cookie}})).status,403);const next=await s.session();s.client.close();await eventually(()=>s.logs.includes('session-ended:device-offline'));assert.equal((await fetch(s.relayURL+'/',{headers:{Cookie:next.cookie}})).status,403);});
test('JSON control endpoints rate limit repeated launch attempts',async t=>{const s=await setup(t);let response;for(let i=0;i<61;i++)response=await s.control('devices');assert.equal(response.status,429);});
test('Supabase verification uses fixed project RPCs and fails closed on API errors',async()=>{let seen;const db=createDatabase({fetcher:async(url,options)=>{seen={url,options};return {ok:true,json:async()=>({})};}});await db.owner(token,{operation:'devices'});assert.match(seen.url,/xfwjzxjeessduxuuqeop\.supabase\.co\/rest\/v1\/rpc\/neon_remote_owner$/);assert.equal(seen.options.headers.Authorization,'Bearer '+token);assert.equal(seen.url.includes(token),false);for(const response of [{ok:false,status:403},{ok:false,status:500}])await assert.rejects(createDatabase({fetcher:async()=>response}).owner(token,{}));});
test('account bridge verifies current owner role before configuration, and strips unknown commands',async t=>{let requests=[];const bridge=createOwnerRelay({getOrigin:()=>undefined,fetcher:async(url,options)=>{requests.push({url,options});return {ok:false};}});const server=http.createServer(bridge),url=await listen(server);t.after(()=>server.close());const response=await fetch(url,{method:'POST',headers:{Origin:account,Authorization:'Bearer '+token},body:'{"operation":"config"}'});assert.equal(response.status,403);assert.equal(requests.length,1);assert.match(requests[0].url,/neon_owner_overview$/);});
test('account bridge reports pending hosting honestly, and never relays to a browser-selected destination',async t=>{let requests=[];const bridge=createOwnerRelay({getOrigin:()=>undefined,fetcher:async(url)=>{requests.push(url);return {ok:true,json:async()=>({players:4})};}}),server=http.createServer(bridge),url=await listen(server);t.after(()=>server.close());const response=await fetch(url,{method:'POST',headers:{Origin:account,Authorization:'Bearer '+token},body:'{"operation":"config","target":"https://evil.test"}'});assert.equal(response.status,200);assert.equal((await response.json()).configured,false);assert.equal(requests.length,1);});
